before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: VrIbMjV/h7WUjkI9jB3WceK5SS3iNYxC8PhK381goFB8hYNB2ykqIdz7aMhyrxR56MPIaVsnhxeRZ9d1ac+iCzRdkPRdVWxe/eH+eqxf9TZDmBmG7/nk4IJOyxo9qRatG+Xj/Ppu4s+kkbCWbnaqdHzYpq+ChKVX5dvFZ/tYTC7Kl2v4oN/rwYOQN7JuDD5kRPgqOA7VNRBBX2SWEqvcfxr80B6oG3G8/RkRXKPyThNumfN5EPbMQkEeaSkCI5BGXAOZBLHvlMtMSIYHgMJEKsJx0I20hfs1FiZM68xmFNeioS1Zxb6pPvth04shTX+uZAmaAYg2uyEmqfGOoDqf8n4Cl1CNpNADzfK/VO37VIjcuOQhXyxkC4lleqUiMtV/9gFtJXf1xvVzUnPvM8k9zGuxZoVXrKzSaXkvt/kYCUvGM2qRZZnfVKjGKPywuAZ7ypZMTWLxjOLA1fKpzeoUHEkUXeKqSh6qv2XQVdezqrwRdkxojs75r7gl17/m+pmS34mz5SBBaMKMEALtmIURxjUX5s0s6N/PeDllTyN+E0e/id9dWKeHJzPVs9nQ96HgjIO/OY2DFIGonCAG2dqc708bZpJVa+NNC44W8Mj8LlT1uAAQpFwSStCHg2uq5JgFNbz2qzdU/iBkLoGIEkGuKtzTEEF77bwiKWUJRlY6sdg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
